### ISSUE TITLE
Give notifiers a configuration option for success/failure events

### ISSUE THREAD

**Issue by fdocr** [fdoxyz/martilla#7]
I'm thinking a configuration for the [Notifier base class](https://github.com/fdoxyz/martilla/blob/master/lib/martilla/notifier.rb) would be helpful to disable success/error notifications. It should work with this layout in the configuration file:

```yaml
notifiers:
- type: 'slack'
  options:
    slack_channel: '#backups'
    slack_webhook_url: https://hooks.slack.com/services/XXXXX/YYYYY/ZZZZZ
    on_failure:  false
    on_success: true
```

Both options should default to `true`
